CREATE TABLE `user_info` (
	`ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`USER_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '用户名',
	`USER_CODE` VARCHAR(50) NULL DEFAULT NULL,
	`USER_TEL` VARCHAR(50) NULL DEFAULT NULL,
	`USER_PWD` VARCHAR(200) NOT NULL,
	`ACTIVE_FLAG` CHAR(2) NOT NULL COMMENT '用户状态',
	PRIMARY KEY (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
